# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               glucode
tagline:             'A simple API for T1 diabetic blood glucose monitoring'
description:         'Made by <a href="https://twitter.com/iamporterhaus" target="_blank">@iamporterhaus</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             '/glucode'
paginate:            5

# About/contact
author:
name:              Mark Otto
url:               https://twitter.com/mdo
email:             markdotto@gmail.com

# Custom vars
version:           1.0.0
appname:           meter
